### ISSUE TITLE
Quest - Plug the Sinkholes

### ISSUE THREAD

**Issue by rmcendre** [RR2739-VCN/Redrum-PvP#54]
unable to set blow up the holes
can set the bombs, they will not go off and seal the hole to complete the quest
tried at both sets of holes.

**Comment by D-CellX** [comment]
Fixed. Please test

**Comment by Thebeus** [comment]
I tested it now and it is still not working. Issue seems to be the same.

**Comment by D-CellX** [comment]
Possibly a reboot is required to take effect. Will investigate now
